export default [
  {
    id: "q1",
    text: "What is the largest lake in the world?",
    answers: [
      // "A library to build user interfaces with help of declarative code.",
      // "A library for managing state in web applications.",
      // "A framework to build user interfaces with help of imperative code.",
      // "A library used for building mobile applications only.",
      "Baikal",
      "Caspian Sea",
      "Lake Superior",
      "Ontario",
    ],
  },
  {
    id: "q2",
    text: "Ecology deals with?",
    answers: [
      "Relation between organisms and their environment",
      "Birds",
      "Cell formation",
      "Tissues",
      // "Enabling the use of state and other React features in functional components.",
      // "Creating responsive layouts in React applications.",
      // "Handling errors within the application.",
      // "Part of the Redux library for managing global state.",
    ],
  },
  {
    id: "q3",
    text: "Which is the largest island?",
    answers: [
      "Greenland",
      "New Guinea",
      "Andaman Nicobar",
      "Hawaii",
      // "A JavaScript extension that adds HTML-like syntax to JavaScript.",
      // "A JavaScript library for building dynamic user interfaces.",
      // "A specific HTML version that was explicitly created for React.",
      // "A tool for making HTTP requests in a React application.",
    ],
  },
  {
    id: "q4",
    text: "What do Koalas usually eat?",
    answers: [
      "Eucalyptus",
      "Bamboo",
      "Aloe Vera",
      "Banana",
      // "By defining a JavaScript function that returns a renderable value.",
      // "By defining a custom HTML tag in JavaScript.",
      // "By creating a file with a .jsx extension.",
      // 'By using the "new" keyword followed by the component name.',
    ],
  },
  {
    id: "q5",
    text: "What is the phobia of thunder and rain?",
    answers: [
      "Ombrophobia",
      "Acrophobia",
      "Claustrophobia",
      "Agoraphobia",
      // "An object in a component that holds values and may cause the component to render on change.",
      // "The lifecycle phase a React component is in.",
      // "The overall status of a React application, including all props and components.",
      // "A library for managing global state in React applications.",
    ],
  },
  {
    id: "q6",
    text: "What does Carpe Diem mean in Latin?",
    answers: [
      "Enjoy the moment",
      "Have no fear",
      "Sorry I blew it",
      "Hello",
      // "By using the map() method to iterate over an array of data and returning JSX.",
      // "By using the for() loop to iterate over an array of data and returning JSX.",
      // "By using the forEach() method to iterate over an array of data and returning JSX.",
      // "By using the loop() method to iterate over an array of data and returning JSX.",
    ],
  },
  {
    id: "q7",
    text: "What is considered the lung of the Earth?",
    answers: [
      "Amazon rainforest",
      "The Mississippi River",
      "The Sahara",
      "Everest",
      // "Using a the #if template syntax.",
      // "Using a ternary operator.",
      // "Using the && operator.",
      // "Using an if-else statement.",
    ],
  },
];
